### ISSUE TITLE
Cannot Re-enumerate

### ISSUE THREAD

**Issue by ghost** [skgmn/fromjs#4]
I'm not sure if this is the intended functionality but since lazy evaluation is already in place. The following snippet might be expected to have ['value'] as it's output

var array = [];
var x = from(array);
x.toArray();
//-->[]
array.push('value');
x.data
//-->['value']
x.toArray();
//-->[] 
//ideal output of toArray() would reflect x.data

**Comment by ghost** [comment]
The ObjectIterable does not behave this way. Only an ArrayIterable.

**Comment by skgmn** [comment]
Sorry for a late answer. That is not a bug.
_from_() works under the assumption that given collection is **read-only**.
(I had to mention it in README. I apologize for it.)

So after a collection has changed, _from_() has to be called again about the collection.
This inconvenience is a victim of performance optimization, but I think it's a kind of tolerable thing.

**Comment by calebboyd** [comment]
Hmm. Interesting. Can you explain why this is not the case when using an object iterable? (if array ops are replaced with object ops in the above snippet). 

This is actually very desirable especially in the event you want to have an Iterable ("IQueryable") wrapping a collection that you continually want change and subsequently to 'query'

**Comment by skgmn** [comment]
Each ArrayIterable instance contains a 'range information' inside itself. The information is cached when query is executed and the cache is valid through consequent queries. The cache needs to be cleared whenever the collection is changed to re-enumerate properly, but there's no common way to observe the changes of collection currently. That's why the problem occurs, while ObjectIterable which doesn't have any cache mechanism works well.

However, after I considered about it a few days, I concluded the cache mechanism is not vital. So I will try to fix it soon.

**Comment by calebboyd** [comment]
Great! Thanks for looking into that. The alternative works in this aspect.. But as you're probably aware, is slow.
